#!/bin/bash

#DEBHELPER#

REPORT=$(($RANDOM%5));
RECHECK=$(($RANDOM%30));
OVERLIM=$(($RANDOM%30));
TOUCH=$((RANDOM%30));
RECALC=$((RANDOM%60));
COREC=$((RANDOM%60));
CHECKGPU=$((RANDOM%5));

echo "MAILTO=vchlumsky@cesnet.cz" >/etc/cron.d/torque-meta-mom
echo "${REPORT}-59/5 * * * * root /var/spool/torque/mom_scripts/report_scratch" >>/etc/cron.d/torque-meta-mom
echo "${RECHECK}-59/30 * * * * root /var/spool/torque/mom_scripts/recheck_leftover_scratch" >>/etc/cron.d/torque-meta-mom
echo "${OVERLIM}-59/30 * * * * root /var/spool/torque/mom_scripts/check_scratch_usage" >>/etc/cron.d/torque-meta-mom
echo "${TOUCH}-59/30 * * * * root /var/spool/torque/mom_scripts/touch_scratch" >>/etc/cron.d/torque-meta-mom
echo "${RECALC} 2 * * * root /var/spool/torque/mom_scripts/recalculate_leftover_scratch" >>/etc/cron.d/torque-meta-mom
echo "${COREC} 4 * * * root /var/spool/torque/mom_scripts/pbs_get_cores" >>/etc/cron.d/torque-meta-mom
echo "${CHECKGPU}-59/10 * * * * root /var/spool/torque/mom_scripts/recheck_gpu_allocations" >>/etc/cron.d/torque-meta-mom
